# ai_gpu_grid_sim/config.yaml

# System-Level Configuration
num_gpus: 16             # Number of GPUs (must be a perfect square: 4, 16, etc.)
topology: "fat_tree"         # Network topology (currently only mesh is supported)
fat_tree_k: 4 # Port count of switches (must be even)
random_seed: 42
# Traffic Configuration
# Options: "uniform_random", "transpose", "hotspot"
traffic_pattern: "uniform_random" 
injection_rate: 0.05
hotspot_nodes: [5]
hotspot_rate: 0.5
routing_algo: "XY" 
congestion_threshold: 0.75
num_virtual_channels: 4
router_buffer_size: 8
simulation_cycles: 2000   # Total number of cycles to run the simulation

# --- Future parameters from your spec can be added here ---
# vc_per_port: 2
# flit_width_bits: 64
# router_buffer_size: 4