architecture: "hybrid_electrical" 
num_gpus: 16             
random_seed: 42


topology: "mesh"
fat_tree_k: 4 
hybrid_electrical_config:
  secondary_topology: "fat_tree"
  secondary_traffic: ["all_reduce"]

traffic_pattern: "all_reduce" 
injection_rate: 0.05
hotspot_nodes: [5]
hotspot_rate: 0.5

routing_algo: "adaptive" 
congestion_threshold: 0.75
num_virtual_channels: 4
router_buffer_size: 8
simulation_cycles: 3000   